[project]
name = 'decentralized-marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 2
epoch = 2.5

[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.token]
path = 'contracts/token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
